### ISSUE TITLE
Deployment?

### ISSUE THREAD

**Issue by diff-by-default** [bmarquismarkail/SpaceBaby.Stardew#3]
Is there a reason this hasn't been pushed to nexusmods yet? I just wanna update my collection :(

Have you looked into any sort of auto deployment to make this easier? I think there are github actions that can do this (https://github.com/marketplace/actions/upload-mod-to-nexusmods-thunderstore) I've never tried using em but could be worth looking in to.

I've been testing the fork with the 1.6 changes for a few days now and they seem fine, just curious why this is merged but not updated on the nexus.

**Comment by bmarquismarkail** [comment]
Sorry, at the time, I was flying to attend a funeral. I planned on releasing it yesterday, but I was too jet lagged.

I highly considered it, but never got around with doing so, I will look into it now that I am home.

**Comment by diff-by-default** [comment]
Condolences.

Yeah I haven't tried the gh action I linked like I said, but could be a convenience to get it set up to auto-publish to the nexus. The tradeoff of setup cost vs how long it actually takes to manually publish to nexus once every 3 years though-- that's the real question hah. Not like we get a mod breaking update twice a week out of concernedape.

You can take my impatience on getting an update as a compliment though--this mod is so good it feels critical to every one of my save files until the end of time.

**Comment by bmarquismarkail** [comment]
It is deployed. Thank you!
